[package]
name = "replace-markdown-links"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.26", features = ["derive"] }
regex = "1.11.1"
walkdir = "2.5.0"
